#:schema node_modules/wrangler/config-schema.json
name = "counter"
main = "src/index.js"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

# wrangler.toml (wrangler v3.78.6^)
[observability]
enabled = true


[[durable_objects.bindings]]
name = "COUNTERS"
class_name = "Counter"

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

